language: node_js
node_js:
- lts/boron
- node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: caV6iClw8/L2pYErGHbT+RYMgRCjuBi3YgurSoktlmRxN0nxuzxOg/I6T+dU4MJ6NRvu6x1u5YYcfoaKN7KdfgUrpC14wvKLP+A0ixsfOev9uCTabNEJF7LAlJJuXMFLtlIb4SyiNvLxwxrrCipewq1hAgbLUAQKdYjRqfJd/IXXBYIhWX6VKTytnQzBzr8U5K2mguLbEkcD8pucrYXJLSTYTz6NtuFCmqUUl3aSKpfDayuTFbENlGJNELCZ36c4x0i3sTz9Y57sJPocP775S1767OfCngcUjA1nAA3MR+Ap9rSsN2ErdZt7T4BZbN9gAY59wGY/XlUqP6/EgSHHZ43IRPyptU53GojNMIQYRvXqR9dHCUQcozXKa7KIuqrfodKN2iYdK4ivojcOQYkjHRkH+tK+t03LPNu4yQ2mRpxmYvDmtPxlXo6e8HN7iSu2V5aV35ZX5O0lZx2XNTHi7rxA/NYt7V2YqoRjY/fV4JxzTzf/AITRSclLPHJ7kMjEA6eTTp6GflP8HvhTMWQ2Z1e2AgYIFCTUNHNZtsX3Wbi0rlHsgse/DTwvh7sd2MxHQ/eQdFKOnESwfkot5T0tNrTQ061zgQCkefUu+jfWYL/3D/WeRw517GvzkvYwHhZ83QaEnL8py10H32sOBNdMNld6WFKYiilIlIB44rU9Xxk=
  file:
    - "vendors.js"
    - "vendors.min.js"
  on:
    tags: true
