language: node_js
node_js:
- '4.0'
- '8.0'
deploy:
  provider: releases
  api_key:
    secure: PNuYybLguX/MK1IeC7/s4ADZICHixosLwC83uWfumcPkeCudK3wHMKrNCrbCW+y1um5YzIo75X1Dx5KN+GllR236JfsLBmcl6t+LwKa2zZNV8/1T6RxfW2lBUJVTz3EW72EIiBvVK2kXHP3jb8x2+DA5xzVRVbVOnofcSJ3t+7gqJtP4j47YPvKO8nlveW87Do5WBrORyuDhrp/whxbl6Y0SIcSBPK3Kj8W55spHqSS6xJSzAOn3OFk9PKwnVBJbqHJ4/QZJKC1WstbCux8zWFy0cxB2J8a59hLzVZbmpU6NNu5KgBa/GRHt/G6pjIOuAwR0QEfEiezGTQ1egzwlDk0y0EoVG1QgQ3buWtamduyFhLPLhnNY2PRq53P48vm+THbSD9LcOPMoyG0WnY0ehapNInKXletmjfqGlRxe0mYNcjDmJSeoIHRhyAe0vD6Y9ktxtkD0D5NPJTT0T9NAKiA7CeVCHkuurPO7GeP7AOK6EZ64jxFt8DZ50q1pYv98sYJwsAzZawKIRRue7AWdNVQAmhTaeVYIe2cHzKxZVRbl0J+/Y4DQljzB+ELAMtEwy8pJGrl2OQTuM3DqhWLKH+vXcH0YKZhMaAyXKGzCO+q+DWEQc79Evyz8OMdJye+jAGxmfafRg8MyNXINJoB4mO1yw0RU51VKKHDdRbxbktM=
  file:
    - "vendors.js"
    - "vendors.min.js"
  on:
    tags: true
    node: '8.0'
